// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getParamsEP_priorMean_algo1_cpp
Rcpp::List getParamsEP_priorMean_algo1_cpp(arma::mat X, arma::vec y, arma::vec priorMean, double nu2, double tolerance, int maxIter);
RcppExport SEXP _fragcorr_getParamsEP_priorMean_algo1_cpp(SEXP XSEXP, SEXP ySEXP, SEXP priorMeanSEXP, SEXP nu2SEXP, SEXP toleranceSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type priorMean(priorMeanSEXP);
    Rcpp::traits::input_parameter< double >::type nu2(nu2SEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(getParamsEP_priorMean_algo1_cpp(X, y, priorMean, nu2, tolerance, maxIter));
    return rcpp_result_gen;
END_RCPP
}
// FAStCDF_algo1_cpp
double FAStCDF_algo1_cpp(const NumericVector& x, const NumericMatrix& Sigma, bool logp, double eps, double tolerance, int maxIter);
RcppExport SEXP _fragcorr_FAStCDF_algo1_cpp(SEXP xSEXP, SEXP SigmaSEXP, SEXP logpSEXP, SEXP epsSEXP, SEXP toleranceSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type logp(logpSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(FAStCDF_algo1_cpp(x, Sigma, logp, eps, tolerance, maxIter));
    return rcpp_result_gen;
END_RCPP
}
// loglik_all_patterns
NumericMatrix loglik_all_patterns(CharacterVector fragment, CharacterVector dist_sub, CharacterVector M_str, CharacterVector N_str, NumericVector phi, NumericVector s, double eps, int min_n, bool use_bvn, int print_every);
RcppExport SEXP _fragcorr_loglik_all_patterns(SEXP fragmentSEXP, SEXP dist_subSEXP, SEXP M_strSEXP, SEXP N_strSEXP, SEXP phiSEXP, SEXP sSEXP, SEXP epsSEXP, SEXP min_nSEXP, SEXP use_bvnSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fragment(fragmentSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dist_sub(dist_subSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type M_str(M_strSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type N_str(N_strSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bvn(use_bvnSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_all_patterns(fragment, dist_sub, M_str, N_str, phi, s, eps, min_n, use_bvn, print_every));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fragcorr_getParamsEP_priorMean_algo1_cpp", (DL_FUNC) &_fragcorr_getParamsEP_priorMean_algo1_cpp, 6},
    {"_fragcorr_FAStCDF_algo1_cpp", (DL_FUNC) &_fragcorr_FAStCDF_algo1_cpp, 6},
    {"_fragcorr_loglik_all_patterns", (DL_FUNC) &_fragcorr_loglik_all_patterns, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_fragcorr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
