# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getParamsEP_priorMean_algo1_cpp <- function(X, y, priorMean, nu2, tolerance, maxIter = 1e4L) {
    .Call(`_fragcorr_getParamsEP_priorMean_algo1_cpp`, X, y, priorMean, nu2, tolerance, maxIter)
}

FAStCDF_algo1_cpp <- function(x, Sigma, logp = FALSE, eps = 2.0, tolerance = 1e-5, maxIter = 1000000L) {
    .Call(`_fragcorr_FAStCDF_algo1_cpp`, x, Sigma, logp, eps, tolerance, maxIter)
}

#' Log-likelihood of each fragment under each correlation pattern
#'
#' @param fragment  character, the C/T/. string of each fragment
#' @param dist_sub  character, comma-separated bp gaps between consecutive CpGs
#' @param M_str,N_str character, comma-separated methylated / total counts
#' @param phi,s     the patterns; rho(d) = phi * exp(-d / s)
#' @param eps       clamp on the per-site methylation rate
#' @param min_n     minimum read depth for a site to be used
#' @param use_bvn   closed-form bivariate normal when exactly two sites are used
#' @return a matrix, one row per fragment and one column per pattern
loglik_all_patterns <- function(fragment, dist_sub, M_str, N_str, phi, s, eps = 1e-6, min_n = 5L, use_bvn = FALSE, print_every = 200000L) {
    .Call(`_fragcorr_loglik_all_patterns`, fragment, dist_sub, M_str, N_str, phi, s, eps, min_n, use_bvn, print_every)
}

